Algoritmo "2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professora   : Fernanda
// Descrição   : 2
// Autor(a)    : Joao Vitor Da Silva Arruda Moreira
// Data atual  : 04/12/2024
Var
// Seção de Declarações das variáveis 

 Numero1:inteiro
 Anterior: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Escreva um numero")
Leia(Numero1)
Anterior <-(numero1 + 1)
escreva(numero1 + 1)

Fimalgoritmo