Algoritmo "PARA(2)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
  i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Para i de 10 ate 1 passo -1 faca
      Escreval(i)
   FimPara
Fimalgoritmo