Algoritmo "rep3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda
// Descrição   :
// Autor(a)    :joao vitor da silva arruda moreira
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 
  i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para i de 10 ate 1 passo -1 faca
      escreval(i)
   fimpara

Fimalgoritmo