Algoritmo "rep4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joao vitor da silva
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 

i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i de 15 ate 200 faca
escreval("O quadrado de ", i, " é: ", i * i)
fimpara
   
Fimalgoritmo