Algoritmo "exercicio (b)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda
// Descrição   : exercicios da aula
// Autor(a)    : Joao vitor da silva arruda moreira
// Data atual  : 09/12/2024
Var

   valor: real

Inicio

   Escreva("Digite um valor: ")
   Leia(valor)


   Se valor >= 0 Entao
      EscrevaL("O valor é POSITIVO.")
      
   Senao
      EscrevaL("O valor é NEGATIVO.")
    fimse

Fimalgoritmo
